name: jafeth deploy
on: [push]
jobs: 
  Explore-Github-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Install packages
        run:  npm ci
      - name: Bundle
        run: npm run build
